controller_manager:
  ros__parameters:
    update_rate: 100
    controller_list:
      - name: diff_drive_base_controller
        type: diff_drive_controller/DiffDriveController
    
diff_drive_base_controller:
  ros__parameters:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel_names: ["left_wheel2base_link"]
    right_wheel_names: ["right_wheel2base_link"]
    wheel_separation: 0.2
    wheel_radius: 0.0325
    publish_rate: 50.0
    enable_odom_tf: true
    cmd_vel_timeout: 0.25
    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]